#caena de texto
"str"
enteros = 5 
flotantes = 5.0
listas = ["contenido mutable",1,2,3] #su contenido puee ser mutable
tuplas = ("contenido inmutable",1,2,3) # su contenido es inamovible 
boleano_v= True
booleano_f= False
Diccionario=[
    "clave":"valor" # el valor puede ser cualquier tipo de dato
    
]

len(lista) #sacar longitud expresada en un numero entero
#recordemos que el indice comienza a partir del numero 0
listas.append("contenido nuevo")# añadimos contenido a la lista
print(diccionario.items())
dick_item([("clave", "valor")])

if booleano_f: #if significa "si", y en caso de que la condicion sea verdadera permite ejecutar el coigo indentado
    print(cadena_de_texto)
elif booleano_v #"elif" sifnifica "si no" , intenta esto

for numero in range(1,11): #=> con la palabra reservada for, declararmos un bucle
# en el cual utilizando la palabra in vamos a determinar que objeto vamos a iterar
  print(numero)
  while True:
    print(cadena_de_texto)
    break #=> rompemos la ejecución del iterador mas cercano, en este caso el while
# "anidar" significa poner un bucle dentro de otro bucle
# también se utiliza para referirse a los condicionales dentro de condicionales

while booleano_v:
# "while" significa "mientras" y va a validar que
# la condición sea verdadera antes de volver a iterar
  print(cadena_de_texto)
  break #=> "break" significa "romper" y va a romper la ejecución de
  # cualquier bucle que se esté iterando en ese momento
  # rompiendo siempre el mas cercano